<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.1.0 .\static\Computer.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/static/Computer.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.LaptopBase.geometry}
      material={gltf.nodes.LaptopBase.material}
      position={[0.01, 0.88, -0.11]}
      rotation={[-0.34, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.LaptopScreen.geometry}
      material={gltf.nodes.LaptopScreen.material}
      position={[0.01, 0.88, -0.11]}
      rotation={[-0.34, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.GlassStand.geometry}
      material={gltf.nodes.GlassStand.material}
      scale={1.69}
    />
    <T.Mesh
      geometry={gltf.nodes.Coffee.geometry}
      material={gltf.nodes.Coffee.material}
      position={[2.39, 0.68, -0.16]}
      rotation={[-0.21, 0.83, -0.37]}
      scale={0.46}
    />
    <T.Mesh
      geometry={gltf.nodes.Foam.geometry}
      material={gltf.nodes.Foam.material}
      position={[2.38, 0.65, -0.14]}
      rotation={[-0.3, 1.22, -0.39]}
      scale={0.31}
    />
    <T.Mesh
      geometry={gltf.nodes.Mug.geometry}
      material={gltf.nodes.Mug.material}
      position={[2.36, 0.58, -0.11]}
      rotation={[-0.21, 0.83, -0.37]}
      scale={0.46}
    />
    <T.Mesh
      geometry={gltf.nodes.Clock.geometry}
      material={gltf.nodes.Clock.material}
      position={[-2.44, 1.48, 0.99]}
      rotation={[0.37, -0.22, -0.05]}
      scale={1.14}
    />
    <T.Mesh
      geometry={gltf.nodes.stars.geometry}
      material={gltf.nodes.stars.material}
      position={[-0.41, -0.04, 5.34]}
      rotation={[1.53, 0, -0.3]}
      scale={[1.46, 1.18, 1.32]}
    />
    <T.Mesh
      geometry={gltf.nodes.bg2.geometry}
      material={gltf.nodes.bg2.material}
      position={[-12.15, 4.37, 17.44]}
      rotation={[0.11, 0.54, 1.46]}
      scale={[3.36, 2.67, 3.51]}
    />
    <T.Mesh
      geometry={gltf.nodes.bg3.geometry}
      material={gltf.nodes.bg3.material}
      position={[2.51, 3.86, 19.38]}
      rotation={[1.21, 1.33, 0.09]}
      scale={[1.19, 0.95, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.bg1.geometry}
      material={gltf.nodes.bg1.material}
      position={[2.51, 3.86, 19.38]}
      rotation={[1.21, 1.33, 0.09]}
      scale={[1.19, 0.95, 1.25]}
    />
    <T.Mesh
      geometry={gltf.nodes.ClockHour.geometry}
      material={gltf.nodes.ClockHour.material}
      position={[-2.44, 1.48, 0.99]}
      rotation={[0.37, -0.22, -0.05]}
      scale={1.14}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
