<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\Computer.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useTexture } from '@threlte/extras'
  import SimpleVert from '../shaders/SimpleVert.glsl?raw'
  import PosterizedColor from '../shaders/PosterizedColorFrag.glsl?raw'
  import ComputerFrag from '../shaders/ComputerFrag.glsl?raw'
  import ComputerVert from '../shaders/ComputerVert.glsl?raw'

  let { fallback=()=>{}, error=()=>{}, children=()=>{}, ref = $bindable(), ...props } = $props()

  const texture = useTexture('/ComputerTexture.png')

  const gltf = useGltf('/Computer.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Laptop_Screen.geometry}
      position={[-0.12, -0.05, 1.35]}
      rotation={[1.47, 0, 0]}
      scale={7.94}>
      <T.MeshBasicMaterial/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Laptop.geometry}
      position={[-0.13, -0.01, 0.66]}
      rotation={[-0.19, 0, 0]}
      scale={0.07}>
      <T.ShaderMaterial
      uniforms={{
        uTexture: { value: $texture },
        uPosterizeValue: { value: 8 }
      }}
      vertexShader={ComputerVert}
      fragmentShader={ComputerFrag}
      attributes={{
        uv: gltf.nodes.Laptop.geometry.attributes.uv
      }}
      />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Laptop_Outline.geometry}
      position={[-0.13, 0, 0.66]}
      rotation={[-0.19, 0, 0]}
      scale={[0.0705, 0.085, 0.0715]}>
      <T.MeshBasicMaterial color="white"/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Table.geometry}
      position={[0.3, -0.1, 0.48]}
      rotation={[-0.19, 0, 0]}
      scale={2.26}>
      <T.MeshBasicMaterial color={0x242C3F}/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Cup.geometry}
      position={[1.89, -0.16, 0.39]}
      rotation={[-0.19, 0.62, 0]}
      scale={0.39}>
      <T.ShaderMaterial
        uniforms={
          {
            uColor: {value: [1.0, 1.0, 1.0]},
            uPosterizeValue: {value: 8},
            isSideways: {value: false},
          }
        }
        vertexShader={SimpleVert}
        fragmentShader={PosterizedColor}
      />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Cup_Outline.geometry}
      position={[1.89, -0.15, 0.39]}
      rotation={[-0.2, 0.59, -0.01]}
      scale={0.39}>
      <T.MeshBasicMaterial color="white"/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Coffee.geometry}
      position={[1.89, -0.15, 0.39]}
      rotation={[-0.2, 0.59, -0.01]}
      scale={0.4}>
      <T.ShaderMaterial
        uniforms={
          {
            uColor: {value: [0.55, 0.33, 0.0]},
            uPosterizeValue: {value: 8},
            isSideways: {value: true},
          }
        }
        vertexShader={SimpleVert}
        fragmentShader={PosterizedColor}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
