<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\joseh.EMANUELLE\Pictures\Projects\portifolio_Herbert\static\Computer.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useTexture } from '@threlte/extras'

  let { fallback=()=>{}, error=()=>{}, children=()=>{}, ref = $bindable(), ...props } = $props()

  const texture = useTexture('/ComputerTexture.png')

  const gltf = useGltf(
    '/Computer.glb'
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Tela.geometry}
      material={gltf.nodes.Tela.material}
      position={[-0.12, -0.12, 1.24]}
      rotation={[1.656, 0, 0]}
      scale={7.8}>
      <T.MeshStandardMaterial color="white"/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Corpo.geometry}
      material={gltf.nodes.Corpo.material}
      position={[-0.13, 0.06, 0.58]}
      scale={0.07}
      on:create={(mesh) => {
        // Replace only the map of the material
        mesh.material.map = $texture
        mesh.material.needsUpdate = true
      }}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
