<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ..\lib\assets\planet.glb
-->

<script lang="ts">
  import { T } from '@threlte/core';
  import { useGltf } from '@threlte/extras';
  import CloudFrag from '../shaders/CloudFrag.glsl?raw';
  import simpleVert from '../shaders/SimpleVert.glsl?raw';
  import PlanetFrag from '../shaders/PlanetFrag.glsl?raw';

  let { fallback=()=>{}, error=()=>{}, children=()=>{}, ref = $bindable(), ...props } = $props();
  let planet_color = $state([Math.random(), Math.random(), Math.random()]);
  let planet_water = $state([Math.random(), Math.random(), Math.random()]);

  let random_continents = $state(getRandomIntInclusive(2,20));
  let random_clouds = $state(getRandomIntInclusive(2,7));

  let satelite_color = $state([Math.random(), Math.random(), Math.random()]);

  const gltf = useGltf(`${import.meta.env.BASE_URL}Space.glb`);

  function getRandomIntInclusive(min: number, max: number) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
  <!--Planet Section-->
  <T.Mesh
    geometry={gltf.nodes.Planet.geometry}
  >
    <T.ShaderMaterial
      uniforms={
        {
          uplanet_water: {value: planet_water},
          uplanet_grass: {value: planet_color},
          planet_random_gen: {value: random_continents},
          posterizer_value: {value: 8.0},
        }
      }
      vertexShader={simpleVert}
      fragmentShader={PlanetFrag}
    />
  </T.Mesh>
  <T.Mesh
    geometry={gltf.nodes.Atmosphere.geometry}
    scale={1.11}>
    <T.ShaderMaterial
      uniforms={
        {
          cloud_random_gen: {value: random_clouds},
          posterizer_value: {value: 8.0},
        }
      }
      vertexShader={simpleVert}
      fragmentShader={CloudFrag}
    />
  </T.Mesh>

  <!--Satelite Section-->
  <T.Mesh
    geometry={gltf.nodes.Satelite.geometry}
    position={[-1.85, 0.74, 1.44]}
    scale={0.35}>
    <T.ShaderMaterial
      uniforms={
        {
          uplanet_water: {value: satelite_color},
          uplanet_grass: {value: satelite_color},
          planet_random_gen: {value: 25},
          posterizer_value: {value: 3.0},
        }
      }
      vertexShader={simpleVert}
      fragmentShader={PlanetFrag}
    />
  </T.Mesh>
  <T.Mesh
    geometry={gltf.nodes.Trajectory.geometry}
    rotation={[-0.01, 0.52, -0.01]}
    scale={[1.06, 1.85, 0.82]}>
    <T.MeshBasicMaterial 
      color={"white"}/>
  </T.Mesh>

  <!--Outline Section-->
  <T.Mesh
    geometry={gltf.nodes.Planet_outline.geometry}
    scale={1.01}>
    <T.MeshBasicMaterial 
      color={"white"}/>
  </T.Mesh>
  <T.Mesh
    geometry={gltf.nodes.Satelite_outline.geometry}
    position={[-1.85, 0.74, 1.44]}
    scale={0.36}>
    <T.MeshBasicMaterial 
      color={"white"}/>
  </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>