<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ..\lib\assets\planet.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import simpleFrag from '../shaders/SimpleFrag.glsl?raw';
  import simpleVert from '../shaders/SimpleVert.glsl?raw';
  import PlanetFrag from '../shaders/PlanetFrag.glsl?raw';

  let { fallback=()=>{}, error=()=>{}, children=()=>{}, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/planet.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Sphere.geometry}
    >
      <T.ShaderMaterial
        vertexShader={simpleVert}
        fragmentShader={PlanetFrag}
      />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Sphere001.geometry}
      scale={1.11}
    >
      <T.ShaderMaterial
        vertexShader={simpleVert}
        fragmentShader={simpleFrag}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
