<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Users\joseh.EMANUELLE\Pictures\Projects\portifolio_Herbert\static\Space.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf(
    '/C:\Users\joseh.EMANUELLE\Pictures\Projects\portifolio_Herbert\static\Space.glb'
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Planet.geometry}
      material={gltf.materials['Material.003']}
    />
    <T.Mesh
      geometry={gltf.nodes.Atmosphere.geometry}
      material={gltf.materials['Material.002']}
      scale={1.11}
    />
    <T.Mesh
      geometry={gltf.nodes.Satelite.geometry}
      material={gltf.materials['Material.003']}
      position={[-1.85, 0.74, 1.44]}
      scale={0.35}
    />
    <T.Mesh
      geometry={gltf.nodes.Trajectory.geometry}
      material={gltf.materials['Material.002']}
      position={[0, 0.09, 0]}
      rotation={[0.11, 0, 0]}
      scale={1.11}
    />
    <T.Mesh
      geometry={gltf.nodes.Satelite_outline.geometry}
      material={gltf.materials['Material.003']}
      position={[-1.85, 0.74, 1.44]}
      scale={0.36}
    />
    <T.Mesh
      geometry={gltf.nodes.Planet_outline.geometry}
      material={gltf.materials['Material.003']}
      scale={1.02}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
