<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\Stars.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback=()=>{}, error=()=>{}, children=()=>{}, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/Stars.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}

    <T.Mesh
      geometry={gltf.nodes.Stars.geometry}
      position={[-25.44, -4.41, -39.47]}
      rotation={[1.6, 0.28, -0.44]}
      scale={2.27}>
        <T.MeshBasicMaterial color="white"/>
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Stars_1.geometry}
      position={[-20.45, -40.97, -22.12]}
      rotation={[1.37, 0.58, -0.42]}
      scale={2.27}>
      <T.MeshBasicMaterial color="white"/>
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
